### ISSUE TITLE
Colab notebook doesn't work. rdkit not found

### ISSUE THREAD

**Issue by churnikov** [MolecularAI/aizynthfinder#101]
Hi!

I tried to use colab notebook, but it didn't work because rdkit could not be found.

But installing rdkit-pypi worked for me. Can I suggest you use rdikit-pypi instead of conda ones? I can create PR for that :)

**Comment by SGenheden** [comment]
Thank you for your feedback.
The Colab notebook is a bit outdated, you made me realize.
The latest version of AiZynthFinder can be installed with pip, and this uses the rdkit from pypi. 
Please go ahead and prepare a PR with an update notebook.

**Comment by churnikov** [comment]
Hi!

In this PR I made it so that the latest release is always pulled.
https://github.com/MolecularAI/aizynthfinder/pull/102

**Comment by SGenheden** [comment]
Thanks for the PR. Sorry it took so long for me to merge the PR.
