### ISSUE TITLE
can not see json file for tree

### ISSUE THREAD

**Issue by hongxianglics** [MolecularAI/aizynthfinder#113]
Hi 

I was using the `aizynthcli` from command for a single SMILES and I could get the output in the command. But you said the `tree` should be generated in a `json` file which I have not found yet. Could you please tell me where is the file locate?

Best,

Hongxiang

**Comment by hongxianglics** [comment]
why no body answer me :(

**Comment by SGenheden** [comment]
It should be in the same folder as you execute  the script, unless you provide another filename/path to `aizynthcli`

**Comment by hongxianglics** [comment]
Thanks, although I still cannot find it, I can use the python interface instead.
