### ISSUE TITLE
error when using CLI for molecules from file

### ISSUE THREAD

**Issue by hongxianglics** [MolecularAI/aizynthfinder#114]
Hi,

I am interested in your tool and try to use the command to calculate molecules from file. I used `aizynthcli --config config.yml --smiles molecules.txt` in which `molecules.txt` is the file contains my molecule smiles. 
But I got the error below
<img width="949" alt="AIZ fail" src="https://user-images.githubusercontent.com/104338096/233499225-7039f7b8-9513-4f1b-b752-df188c7dbc04.png">
and my `molecules.txt` is very simple with only one sample molecule from your document.
<img width="701" alt="molecule" src="https://user-images.githubusercontent.com/104338096/233499301-d69ffa9f-df8b-46f0-b758-ae68f1b938ed.png">

Could you please help me look at this？

Thanks!

**Comment by SGenheden** [comment]
If you have the double quotes in the input file, that is an error. Each line should just have one, plain SMILES string

**Comment by hongxianglics** [comment]
Got it! Thanks!
