### ISSUE TITLE
question about python interface

### ISSUE THREAD

**Issue by hongxianglics** [MolecularAI/aizynthfinder#115]
Hi,

When I was using the python interface with the code in the graph:
<img width="506" alt="python AIZ" src="https://user-images.githubusercontent.com/104338096/233502919-8c369bfd-8d5a-4814-9dcb-4d8e31134f9c.png">
I could get the result in the graph below:
<img width="766" alt="python result" src="https://user-images.githubusercontent.com/104338096/233502964-47824737-e2c2-4159-8f91-b9c2028e5adf.png">
but I could only see the precursor of the first step and could not see the intermediate and whole search tree. 
I know you have a GUI to show search tree but I want to do batch search, is there a way to do batch search and get all the search tree?

Thanks!

**Comment by SGenheden** [comment]
If you use the Python interface, this is how you obtain the a list of dictionaries containing the synthetic routes:
``
trees = finder.routes.dicts
``
or if you are interested in the images
``
images = finder.routes.images
``
the `finder.routes` is an intance of a `RouteCollection` class that you can find more documentation about here: https://molecularai.github.io/aizynthfinder/aizynthfinder.analysis.html#module-aizynthfinder.analysis.routes

**Comment by hongxianglics** [comment]
Thanks very much! It works well!
