### ISSUE TITLE
Recurring Issue with Jupyter interface

### ISSUE THREAD

**Issue by aa0929** [MolecularAI/aizynthfinder#128]
**This is the hint given by jupyter**
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[1], line 3
      1 from aizynthfinder.interfaces import AiZynthApp
      2 configfile=r"C:\Users\bo jin\config.yml"
----> 3 app = AiZynthApp(configfile)[](url)
File ~\.conda\envs\aizynth-env\lib\site-packages\aizynthfinder\interfaces\aizynthapp.py:60, in AiZynthApp.__init__(self, configfile, setup)
     57 def __init__(self, configfile: str, setup: bool = True) -> None:
     58     # pylint: disable=used-before-assignment
     59     setup_logger(logging.INFO)
---> 60     self.finder = AiZynthFinder(configfile=configfile)
     61     self._input: StrDict = dict()
     62     self._output: StrDict = dict()

File ~\.conda\envs\aizynth-env\lib\site-packages\aizynthfinder\aizynthfinder.py:67, in AiZynthFinder.__init__(self, configfile, configdict)
     64 self._logger = logger()
     66 if configfile:
---> 67     self.config = Configuration.from_file(configfile)
     68 elif configdict:
     69     self.config = Configuration.from_dict(configdict)

File ~\.conda\envs\aizynth-env\lib\site-packages\aizynthfinder\context\config.py:129, in Configuration.from_file(cls, filename)
    127     txt = txt.replace(item, os.environ[item[2:-1]])
    128 _config = yaml.load(txt, Loader=yaml.SafeLoader)
--> 129 return Configuration.from_dict(_config)

File ~\.conda\envs\aizynth-env\lib\site-packages\aizynthfinder\context\config.py:98, in Configuration.from_dict(cls, source)
     95 src_copy = dict(source)  # Make a copy so we can pop items
     96 config_obj._update_from_config(src_copy)
---> 98 config_obj.expansion_policy.load_from_config(**src_copy.get("policy", {}))
     99 config_obj.filter_policy.load_from_config(**src_copy.get("filter", {}))
    100 config_obj.stock.load_from_config(**src_copy.get("stock", {}))

File ~\.conda\envs\aizynth-env\lib\site-packages\aizynthfinder\context\policy\policies.py:113, in ExpansionPolicy.load_from_config(self, **config)
    111 for key, policy_spec in files_spec.items():
    112     modelfile, templatefile = policy_spec
--> 113     strategy = TemplateBasedExpansionStrategy(
    114         key, self._config, source=modelfile, templatefile=templatefile
    115     )

**Comment by SGenheden** [comment]
Hello,
Please use a more informative title/description in the future.
Also: please provide some details on what you are trying to do with the GUI: what expansion policy are you trying to use? How is your config file looks like?

**Comment by aa0929** [comment]
Hello,thankyou for your reply!
# Here is my config in Win 11：
policy:
  files:
    full_uspto:
      - D:\Download\12334577\full_uspto_03_05_19_rollout_policy.hdf5
      - D:\Download\12334577\full_uspto_03_05_19_unique_templates.hdf5
stock:
  files:
    zinc: home/zinc_stock_17_04_20.hdf5
# Here is my expansion policy:
![image](https://github.com/MolecularAI/aizynthfinder/assets/45788520/412bbe2b-e1e8-4737-9baa-afefd41b1759)
# In addition, I encountered the same problem when using the following config file in Linux,
policy:
  files:
    full_uspto:
      - /home/full_uspto_03_05_19_rollout_policy.hdf5
      - /home/full_uspto_03_05_19_unique_templates.hdf5
stock:
  files:
    zinc: home/zinc_stock_17_04_20.hdf5
# here is the  screenshot in Linux:
![image](https://github.com/MolecularAI/aizynthfinder/assets/45788520/16b15f67-a34a-4fed-8769-97d047f9735c)

**Comment by SGenheden** [comment]
Thanks for the details. The config looks ok with the expansion policy specification (although the stock path appears to be incorrect). 

It appears that there is something else at the end of the error trace, because I have a hard time imagining what is causing a type error at line 113 of policies.py. Could you be so kind and show the full error trace?

**Comment by aa0929** [comment]
#Of course, I corrected the config file, but the error is unchanged
<img width="506" alt="image" src="https://github.com/MolecularAI/aizynthfinder/assets/45788520/83394c6a-ac08-4b1d-a86b-2afbb6cc3200">
![image](https://github.com/MolecularAI/aizynthfinder/assets/45788520/71f6bf18-853e-48f8-ad77-48086479dadd)

**Comment by SGenheden** [comment]
Aha. This is the issue. 
In the latest release we dropped support for Tensorflow by defaults. 
If you now, re-run the "download_public_data" script you should get ONNX files that can be use with the latest version. 
(Alternatively, you can do something like `pip install aizynthfinder[tf]` to install the Tensorflow dependencies, but that is much more work).

**Comment by aa0929** [comment]
#我非常激动的尝试了，之前的错误不在了，但出现新的错误
![image](https://github.com/MolecularAI/aizynthfinder/assets/45788520/d31f22fa-c6e3-4a94-831d-9f539a46068e)
![image](https://github.com/MolecularAI/aizynthfinder/assets/45788520/491309d7-8d1e-4b2d-9a15-0555b653e28f)
![image](https://github.com/MolecularAI/aizynthfinder/assets/45788520/a5ec29c7-d3c6-43c4-a52c-27460c22512c)
![image](https://github.com/MolecularAI/aizynthfinder/assets/45788520/fe103555-f226-46ae-ae07-513848c6b0b4)

**Comment by aa0929** [comment]
#（last Chinese comment mean：）
I was very excited to try it and the previous error is gone, but a new one appears

**Comment by SGenheden** [comment]
The two files you should use for the config are `uspto_model.onnx` and `uspto_templates.csv.gz`.
The config file should be something like this
```
policy:
  files:
    uspto:
      - uspto_model.onnx
      - uspto_templates.csv.gz
    ringbreaker:
      - uspto_ringbreaker_model.onnx
      - uspto_ringbreaker_templates.csv.gz
filter:
  files:
    uspto: uspto_filter_model.onnx
stock:
  files:
    zinc: zinc_stock.hdf5
```

**Comment by aa0929** [comment]
Thank you for your guidance, the problem has been solved, after doing what you said, I also encountered a component loading problem, the following when the solution, will be helpful to those who will follow
【jupyter notebook中ipywidgets插件不显示】https://blog.csdn.net/qxqxqzzz/article/details/93810518
【PermissionError: [Errno 13] Permission denied】https://blog.csdn.net/weixin_62888476/article/details/127768242?ops_request_misc=&request_id=&biz_id=102&utm_term=PermissionError:%20%5BErrno%2013%5D%20Pe&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduweb~default-0-127768242.142^v91^insert_down1,239^v3^insert_chatgpt&spm=1018.2226.3001.4187
【Loading widget...】https://github.com/jupyter-widgets/ipywidgets/issues/2623

**Comment by aa0929** [comment]
thanks!!!
