### ISSUE TITLE
filter select bug

### ISSUE THREAD

**Issue by wangxr0526** [MolecularAI/aizynthfinder#14]
I have tested your code, but have found problems selecting the filtering model.
in aizynthfinder/aizynthfinder/interfaces/aizynthcli.py line 186

![image](https://user-images.githubusercontent.com/59350191/104806517-0cf5f280-5813-11eb-9365-a95b9b2f75ce.png)

    try:
        finder.filter_policy.select(args.policy or finder.filter_policy.items[0])
    except KeyError:
        pass

**Comment by SGenheden** [comment]
Thanks for your feedback.

Is the filter policy specified in the configuration file? E.g.
```
filter:
  files:
    my_policy: /path/to/keras/model/weights.hdf5
```

if that's the case, you need to select to use the filter policy with the ``--policy`` when running the ``aizynthcli`` command

```
aizynthcli --policy my_policy ...
````

**Comment by wangxr0526** [comment]
> Thanks for your feedback.
> 
> Is the filter policy specified in the configuration file? E.g.
> 
> ```
> filter:
>   files:
>     my_policy: /path/to/keras/model/weights.hdf5
> ```
> 
> if that's the case, you need to select to use the filter policy with the `--policy` when running the `aizynthcli` command
> 
> ```
> aizynthcli --policy my_policy ...
> ```
Thank you very much, the problem is solved！👍😊

**Comment by SGenheden** [comment]
Great!
