### ISSUE TITLE
Incompatibility with python 3.8

### ISSUE THREAD

**Issue by saberger** [MolecularAI/aizynthfinder#15]
Hello,
great tool, well done.
I was trying to set it up within a conda env python=3.8.5 (the install description states that it should work on python 3.8)
However rdkit is incompatible with python 3.8

  - rdkit -> python[version='2.6.*|2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3
0a0|>=3.5,<3.6.0a0|3.4.*']

Your python: python=3.8
You could fix this in the description or am I wrong?
Thank you!

**Comment by SGenheden** [comment]
Thanks for you feedback.

RDKit is compatible with python 3.8, if you install RDKit through the `conda-forge` channel (`conda install -c conda-forge rdkit`).
This is also becoming the recommended channel for RDKit installation.

So I have updated the README to reflect this instead.
