### ISSUE TITLE
Some Questions Regarding Expansion Strategies

### ISSUE THREAD

**Issue by lz2021211161** [MolecularAI/aizynthfinder#151]
Hi,

Firstly, in previous inquiries, I discovered a reference to the address https://molecularai.github.io/aizynthfinder/training.html for creating a new extension strategy. However, it seems this address is no longer active. Could you please clarify if this content has been intentionally removed? If so, where can I find it now?

Secondly, I've come across mentions of the latest USPTO model, uspto_keras_model. Could you direct me to where I can access this model?

I apologize for my lack of understanding regarding these matters and would greatly appreciate your assistance in providing clarification. 

Thank you!

**Comment by SGenheden** [comment]
The training was moved to a separate repo called AiZynthTrain: https://github.com/MolecularAI/aizynthtrain 

You can download the latest model with the `download_public_data` tool as explained on the landing page, or downloaded from Zenodo: https://zenodo.org/records/7341155

**Comment by lz2021211161** [comment]
Hi，
Thank you very much for responding to me so quickly.
I found that the filenames downloaded via the 'download_public_data' command are different from those on the website https://zenodo.org/records/7341155. Does this mean that there are different versions of the models?
All the best!

**Comment by SGenheden** [comment]
The name does not matter. The  'download_public_data' downloads the latest version.

**Comment by lz2021211161** [comment]
Thank you for your prompt reply, I have no further questions.
