### ISSUE TITLE
Tarball Version Needs Update for Python 3.10+

### ISSUE THREAD

**Issue by balakrishnaboligerla2022** [MolecularAI/aizynthfinder#162]
The aizynthfinder package currently specifies a tarball version (v3.7.0) that is not compatible with Python 3.10+. The env-users.yml file indicates Python versions >=3.9,<3.11, but the tarball version seems to require Python <3.10.

Issue Details:

File: env-users.yml
Current Tarball Version: v3.7.0 (URL: https://github.com/MolecularAI/aizynthfinder/archive/v3.7.0.tar.gz)
Required Tarball Version: v4.3.0 (or later)
Steps to Reproduce:

Attempt to create a Conda environment using the provided env-users.yml with Python 3.10 or 3.11.
Encounter a version conflict error related to the aizynthfinder package.
Expected Behavior:

The package should either support Python 3.10+ or the version constraints should be updated to reflect the correct compatibility.

Suggested Fix:

Update the tarball version in the env-users.yml file to v4.3.0 or the appropriate version that supports Python 3.10+.

**Comment by SGenheden** [comment]
Hello
The `env-users.yml` is not up to date, and it is not the recommended way to install aizynthfinder. We will remove this yaml-file. Please follow the end-user installation instructions instead.
