### ISSUE TITLE
Acceleration on AiZynthFinder

### ISSUE THREAD

**Issue by XYxiyang** [MolecularAI/aizynthfinder#166]
Thanks for sharing this promising work! I'm currently applying AiZynthFinder to many molecules(~120K), but the speed is quite slow(~30s for single molecule, is that appropriate?). Can I boost this process by using GPUs? Or how can I boost the process?

**Comment by SGenheden** [comment]
Hello,

30s per compound is about what we see as well. That is roughly the best you can get with the default settings.
GPUs will not improve the performance. 
We typically just spread the compounds over a number of CPU - and with this process we can do retrosynthesis for ~100K molecules in a day or so.

**Comment by XYxiyang** [comment]
Thanks for your answer!

Best
