### ISSUE TITLE
Pydantic version

### ISSUE THREAD

**Issue by halx** [MolecularAI/aizynthfinder#169]
Hi,

can you please update to Pydantic 2.x? In this way AiZynthFinder can be more easily installed in the same environment as REINVENT (still many complaints about incompatible packages but none of those seem to matter).

`route_distances/validation.py` then needs to change as follows
```Python
type: str = Field(pattern=r"^mol$")  #pydantic.constr(regex=r"^mol$")
# ...
type: str = Field(pattern=r"^reaction$")
```

Also, pytorch 1.x is a bit old.  From our experience it is no problem to update to the most recent version 2.x.

Many thanks,
Hannes.

**Comment by SGenheden** [comment]
Now the pydantic update is included in the latest pypi release, so considering this done.
