### ISSUE TITLE
Hard dependency on anaconda

### ISSUE THREAD

**Issue by 0x2b3bfa0** [MolecularAI/aizynthfinder#19]
This project only depends on [anaconda][0] because of [rdkit][1], which still doesn't support PyPi packages because of [its native dependencies][2], but this could change relatively [soon][3] (at least [partially][4]). Once that happens, this project could migrate all its dependencies to [poetry][5] or any similarly modern package manager, leaving `conda` as an optional dependency.

This issue is intended as a reminder, and doesn't require any immediate action. Feel free to add it to a [project board][6], leave it open, or simply close it and, optionally, document this in a separate file.

[0]: https://www.anaconda.com/
[1]: https://github.com/rdkit/rdkit
[2]: http://rdkit.blogspot.com/2019/11/why-rdkit-isnt-available-on-pypi.html
[3]: https://github.com/rdkit/rdkit/issues/1812
[4]: https://github.com/rdkit/rdkit/pull/2690
[5]: https://python-poetry.org/
[6]: https://docs.github.com/en/github/managing-your-work-on-github/about-project-boards

**Comment by SGenheden** [comment]
Thanks for this. I think it is a solid idea, and in the perfect world I would like to install the package with a single command. 

The rdkit is one problem that they have working on for several years, so I am not holding my breath that it will be solved anytime soon. 

Another problem is that I rely on graphviz binaries that are not python packages as all - how would you suggest to solve that dependency?

In a near future I would also like to move to the C++ implementation of RDChiral (https://gitlab.com/ljn917/rdchiral_cpp), which also is most easily managed by conda. 

This is what I like with conda: you can mix pure python libraries with compiled libraries that very easily. I would rather that poetry would integrate better with conda, but most python package manager is only written with pure python packages in mind.

**Comment by 0x2b3bfa0** [comment]
:facepalm: So true! No matter what approach we choose, we'll end depending on platform-specific libraries for `dot` rendering, and it looks like there [aren't any](https://github.com/pygraphviz/pygraphviz/issues/167) binary wheels providing the `dot` command-line tool; at least, not yet.

Given poetry and conda can coexist, it may be a good idea to leverage that symbiosis. After experimenting a bit with #21, I noticed that it might actually be a good idea. In fact, it's [somewhat supported](https://github.com/python-poetry/poetry/pull/1432) by the former.

**Comment by 0x2b3bfa0** [comment]
I was also thinking that `graphviz` is probably only being used for the frontend (graphical) part, and it could be also the case for `rdkit`, or so it seems. Would it be posible to separate the backend from the frontend and rely on `conda` only for the latter? This would probably make the integration with https://github.com/deepchem/deepchem/issues/1198#issuecomment-771098205 easier and [probably] wouldn't add any noticeable complexity to the user experience.

**Comment by SGenheden** [comment]
Right now `graphviz` is only a "soft-dependency", as there is no module imports necessary for this. And right now it is mostly used in the Jupyter notebook GUI to display roots. I have experimented with more interactive presentation, but haven't really manage to incorporate all the necessary Javascript in the notebook. 
Also I do think there is a use-case for exporting images of the routes, and for that `graphviz` is essential. 

`rdkit` is a on the other hand a hard dependency as it used in the core of the algorithm.

**Comment by SGenheden** [comment]
As of version 2.4.0 of the package, `poetry` is used to manage dependencies. So will close this issue now.
