### ISSUE TITLE
Reading in raw template library

### ISSUE THREAD

**Issue by robertburbidgedata** [MolecularAI/aizynthfinder#2]
I am generating template_hash with python's hash function which should return an integer but for some reason doesn't always. This causes a problem in preprocess_rollout.py in read_csv in _filter_dataset. The same problem could occur with mixed types in reaction_hash and other columns. I fixed this by using low_memory=False.

**Comment by SGenheden** [comment]
Thanks for the feedback.
First, the python hash function is always returning an integer, it is not possible to define a `__hash__` function for a class that isn't returning an integer (you will get a TypeError exception, if you try). 
Secondly, I don't think that using the `hash()` function for creating the template (or reaction) hash. Have a look at the `hashlib` module.

The template library for the public data was created with this module [https://github.com/reymond-group/CASP-and-dataset-performance/blob/master/template_utils/amol_utils_rdchiral.py](https://github.com/reymond-group/CASP-and-dataset-performance/blob/master/template_utils/amol_utils_rdchiral.py)

the reaction hash is created by the method ``generate_reaction_identifier()``, and the template hash is created by the method ``hash_template()``.
