### ISSUE TITLE
DeepChem

### ISSUE THREAD

**Issue by 0x2b3bfa0** [MolecularAI/aizynthfinder#20]
I've found an interesting project named [DeepChem](https://deepchem.io) that also seems [interested in retrosynthesis](https://github.com/deepchem/deepchem/issues/1198). I think that some sort of collaboration could potentially be mutually beneficial.

**Comment by rbharath** [comment]
Chiming in on this thread from DeepChem! DeepChem tries to offer an integrated suite of machine learning tools for molecules/materials/other scientific systems (See our docs at https://deepchem.readthedocs.io/en/latest/). We'd love to be able to use `aizynthfinder` to provide a good retrosynthesis tool to our users. If this would be of interest to you folks, would be glad to say more what this could look like technically :)

**Comment by SGenheden** [comment]
Hello @0x2b3bfa0 and @rbharath 

Very interesting idea! I have responded to the issue in the deepchem repository, as I believe it is best to continue the discussion there. Hence I will close this issue.

**Comment by 0x2b3bfa0** [comment]
Excellent!
