### ISSUE TITLE
Search procedure stuck

### ISSUE THREAD

**Issue by xiamr** [MolecularAI/aizynthfinder#22]
![image](https://user-images.githubusercontent.com/18632312/106431358-1ab0a680-64a8-11eb-906e-3156cb115611.png)
When analyze above structure, the progress bar is stuck and the output is not complete.
![image](https://user-images.githubusercontent.com/18632312/106431627-81ce5b00-64a8-11eb-82ef-03725cd6afe6.png)
It seems has some kind of bugs inside the app.

**Comment by SGenheden** [comment]
Are you sure it is not complete? It might finish before 100 iterations, if it is unable to do anything more. But in that case it will write a line after the progress bar, saying it is complete.
Otherwise, if I should debug this you have to start sending me a SMILES string to work from.

**Comment by xiamr** [comment]
I found the completion line. But it is really a misleading progress bar. Maybe it  should clear the progress line after completion.

**Comment by SGenheden** [comment]
Great that it worked. 
I can agree with you that it is somewhat misleading - but it was even more misleading before I printed out the "completion line".
I will look into ways to improve this for a future release - but for now, I will close this issue.
