### ISSUE TITLE
Long-term binary artifact storage

### ISSUE THREAD

**Issue by 0x2b3bfa0** [MolecularAI/aizynthfinder#23]
Have you considered using a long-term solution like [Zenodo](https://zenodo.org/) or [GitHub releases](https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository) for storing artifacts like trained models? The former would even link with DOI, and both are as practical as the current Figshare server for retrieving the data.

**Comment by SGenheden** [comment]
I have looked into *Zenodo*, but haven't really understood the benefits. I have plans to archive the releases of the packages on *Zenodo*, but I have no plans to move the current artifacts from Figshare.
I haven't consider *GitHub releases* because I think that has a different purpose and it would involved Git LFS, which I am not a big fan of.

**Comment by 0x2b3bfa0** [comment]
> I have looked into Zenodo, but haven't really understood the benefits.

The most salient difference is [funding and stability](https://about.zenodo.org/infrastructure/), but that's mainly a matter of taste and nothing is futureproof. Nevertheless, it would be nice to have it like some sort of mirror, as you suggest.

> I have plans to archive the releases of the packages on Zenodo, but I have no plans to move the current artifacts from Figshare.

Effectively, moving them might not be a good idea, but mirroring could be useful.

> I haven't consider GitHub releases because I think that has a different purpose [...]

I think having a copy of the artifacts in the same place as the code may be a good future-proof plan, but this is a bit of a stretch of the common use cases.

> [...] _and it would involved Git LFS, which I am not a big fan of._

🙃 &nbsp;&nbsp;Me neither, but GitHub releases doesn't necessarily involve Git-LFS.

**Comment by 0x2b3bfa0** [comment]
By the way: [DVC](https://dvc.org) might interest you for model version control.

**Comment by 0x2b3bfa0** [comment]
I'm closing this issue to avoid unnecessary clutter.

**Comment by SGenheden** [comment]
> By the way: [DVC](https://dvc.org) might interest you for model version control.

Internally at AstraZeneca we are using DVC, but then we also have storage that DVC supports. Unfortunately it does not work together we either Figshare or Zenodo.

**Comment by 0x2b3bfa0** [comment]
@SGenheden, I've accidentally discovered [DAGsHub](https://dagshub.com/) not so long ago, and looks promising. Have you tried it?
