### ISSUE TITLE
Compounds to Procure doesn't shown

### ISSUE THREAD

**Issue by ys0123** [MolecularAI/aizynthfinder#29]
**Describe**
I am trying to use AiZynthApp in jupyter notebook. after show reactions, I can't see a Compounds to Procure.but Solved and Steps are shown correctly.
The procure file (png) exists in the directory (/ tmp / tmp49t5ya0a) but is not displayed.  It may be due to the character encoding, but it may be another reason. 
I'm not sure what is wrong. I would be grateful for any help. 
Thank you!
```
Compounds to Procure
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.8/dist-packages/IPython/core/display.py in _data_and_metadata(self, always_both)
   1292         try:
-> 1293             b64_data = b2a_base64(self.data).decode('ascii')
   1294         except TypeError:

TypeError: a bytes-like object is required, not 'Image'

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
/usr/local/lib/python3.8/dist-packages/IPython/core/formatters.py in __call__(self, obj, include, exclude)
    968 
    969             if method is not None:
--> 970                 return method(include=include, exclude=exclude)
    971             return None
    972         else:

/usr/local/lib/python3.8/dist-packages/IPython/core/display.py in _repr_mimebundle_(self, include, exclude)
   1281         if self.embed:
   1282             mimetype = self._mimetype
-> 1283             data, metadata = self._data_and_metadata(always_both=True)
   1284             if metadata:
   1285                 metadata = {mimetype: metadata}

/usr/local/lib/python3.8/dist-packages/IPython/core/display.py in _data_and_metadata(self, always_both)
   1293             b64_data = b2a_base64(self.data).decode('ascii')
   1294         except TypeError:
-> 1295             raise FileNotFoundError(
   1296                 "No such file or directory: '%s'" % (self.data))
   1297         md = {}

FileNotFoundError: No such file or directory: '<PIL.Image.Image image mode=RGBA size=1200x200 at 0x7F63A1559820>'
```

**Configuration:**
```
RDKit version: 2020.09.5(Build from source)
Host OS: CentOS 7.4
Docker Container:ubuntu 20.04
Python version : 3.8.5
AiZynthFinder version : 2.4.0
```

**Commands:**
I installed boost-1.69.0 from source and it looks like it's working properly.
```
git clone https://github.com/boostorg/boost.git
cd boost
git checkout boost-1.69.0
git submodule update --init --recursive
./bootstrap.sh --with-python=/usr/bin/python3
./b2 --prefix=/usr/local -j18
./b2 install --prefix=/usr/local -j18
```
I also installed rdkit_2020_09_05(from source) and aizynthfinder 2.4.0.
```
# install rdkit
RDBASE=/usr/local/src/rdkit
RDKIT_BRANCH=Release_2020_09_5
git clone https://github.com/rdkit/rdkit.git
cd $RDBASE
git checkout $RDKIT_BRANCH
git submodule update --init --recursive
mkdir build && cd build
cmake -D RDK_BUILD_INCHI_SUPPORT=ON -D PYTHON_EXECUTABLE=/usr/bin/python3 ..
make -j18 .. install
```

```
python3 -m pip install https://github.com/MolecularAI/aizynthfinder/archive/v2.4.0.tar.gz
```

**Comment by SGenheden** [comment]
Thanks for the feedback @ys0123 

It looks like the notebook is unable to display the image correctly. There are a few things, you could explore/try in order to figure this out:
* Try adding `from rdkit.Chem.Draw import IPythonConsole` as the first line of your notebook. This will import some magic notebook stuff, that isn't necessary on all installations, but might be on yours.
* Can you open the image file from the tmp directory in another "image software"? I don't really understand why it created it as an image on disc, but ok.
* After you have gotten this error, create a new cell and try executing `app.finder.analysis.best_node().state.to_image()` where `app` is the name of your GUI instance (is `app` by default).
* Also try executing this `type(app.finder.analysis.best_node().state.to_image())` to see what exactly the type is.

Please come back to me after these explorations and let me know if you managed to get it to work / or what new errors/info you found out.

Also out of curiosity: why are you building RDKit by yourself, and not install it with conda?

**Comment by ys0123** [comment]
Thank you for your reply.
I tried your suggestions and results is below.

> Try adding `from rdkit.Chem.Draw import IPythonConsole` as the first line of your notebook. 

```
from rdkit.Chem.Draw import IPythonConsole
from aizynthfinder.interfaces import AiZynthApp
app = AiZynthApp("./my_folder/config.yml")
```
I already use that code. but I got an error above.

>I don't really understand why it created it as an image on disc, but ok. 

Because / tmp is a temporary directory of ubuntu, So I think it is right to create images in / tmp / tmp49t5ya0a. Is this wrong? 
And I can open images by windows picture viewer. (I don't have image software on ubuntu. So I copied images to windows from ubuntu and I can see it.)

> create a new cell and try executing app.finder.analysis.best_node().state.to_image()

after that I got similar errors.
`app.finder.analysis.best_node().state.to_image()`

TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.8/dist-packages/IPython/core/display.py in _data_and_metadata(self, always_both)
   1292         try:
-> 1293             b64_data = b2a_base64(self.data).decode('ascii')
   1294         except TypeError:

TypeError: a bytes-like object is required, not 'Image'

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
/usr/local/lib/python3.8/dist-packages/IPython/core/formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

/usr/local/lib/python3.8/dist-packages/IPython/core/display.py in _repr_png_(self)
   1311     def _repr_png_(self):
   1312         if self.embed and self.format == self._FMT_PNG:
-> 1313             return self._data_and_metadata()
   1314 
   1315     def _repr_jpeg_(self):

/usr/local/lib/python3.8/dist-packages/IPython/core/display.py in _data_and_metadata(self, always_both)
   1293             b64_data = b2a_base64(self.data).decode('ascii')
   1294         except TypeError:
-> 1295             raise FileNotFoundError(
   1296                 "No such file or directory: '%s'" % (self.data))
   1297         md = {}

FileNotFoundError: No such file or directory: '<PIL.Image.Image image mode=RGBA size=1200x200 at 0x7F6C49458610>'

>type(app.finder.analysis.best_node().state.to_image())

IPython.core.display.Image

> Also out of curiosity: why are you building RDKit by yourself, and not install it with conda?

because of  it's not free recently so I don't want to use anaconda to install rdkit.

Thank you!

**Comment by SGenheden** [comment]
This seems all very mysterious to me. The `IPython.core.display.Image` class should have been initialized with a `data` argument, which should be raw image bytes or a filename on disc. But now it seems to be initialized with a PIL image. However, I cannot see how this happened by looking at the RDKit code.

Could you try to run this code in an empty notebook:
```
from rdkit import Chem
from rdkit.Chem import Draw
smiles_list = [
    "CC(C)Cc1ccc(cc1)C(C)C(=O)O", 
    "CC(OC1=C(C(=O)O)C=CC=C1)=O CC(=O)OC1C=CC=CC=1C(O)=O", 
    "Cc1cnc(c(c1OC)C)CS(=O)c2[nH]c3ccc(cc3n2)OC", 
    "CC(C)c1cccc(c1O)C(C)C"
]
mols = [Chem.MolFromSmiles(smiles) for smiles in smiles_list]
Draw.MolsToGridImage(mols, molsPerRow=2, legends=["ibuprofen", "aspirin", "omeprazole", "propofol"])
```` 
to make clear that it is an RDkit problem.

**Comment by ys0123** [comment]
I tried your code and got a similar error.

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.8/dist-packages/IPython/core/display.py in _data_and_metadata(self, always_both)
   1292         try:
-> 1293             b64_data = b2a_base64(self.data).decode('ascii')
   1294         except TypeError:

TypeError: a bytes-like object is required, not 'Image'

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
/usr/local/lib/python3.8/dist-packages/IPython/core/formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

/usr/local/lib/python3.8/dist-packages/IPython/core/display.py in _repr_png_(self)
   1311     def _repr_png_(self):
   1312         if self.embed and self.format == self._FMT_PNG:
-> 1313             return self._data_and_metadata()
   1314 
   1315     def _repr_jpeg_(self):

/usr/local/lib/python3.8/dist-packages/IPython/core/display.py in _data_and_metadata(self, always_both)
   1293             b64_data = b2a_base64(self.data).decode('ascii')
   1294         except TypeError:
-> 1295             raise FileNotFoundError(
   1296                 "No such file or directory: '%s'" % (self.data))
   1297         md = {}

FileNotFoundError: No such file or directory: '<PIL.Image.Image image mode=RGBA size=400x400 at 0x7F51B0282B50>'

<IPython.core.display.Image object>
```

I think this is problem of rdkit or boost. So I open an issue in rdkit.
But  I should use conda (I don't want to), and the problem isn't solved. 

[Draw.MolsToGridImage doesn't work ?? #3937](https://github.com/rdkit/rdkit/issues/3937)
[CMake Error:Could not find a package configuration file provided by "boost_python" #3913](https://github.com/rdkit/rdkit/issues/3913)

I built rdkit and boost from source. 
Do you have any ideas?
Thanks!

**Comment by SGenheden** [comment]
Ok. This is purely an RDKit / Boost problem. Therefore, I will close this issue for now. 

I do not have any ideas to provide with regards to building either rdkit or boost from source. I have never had to do it (and wouldn't want to do it either). My suggestion is to use the conda package, and use this problem as a motivation why you need this even though it would cost your company money.
