### ISSUE TITLE
How to get the Reaxys data to retrain aizynthfinder?

### ISSUE THREAD

**Issue by queliyong** [MolecularAI/aizynthfinder#32]
Hi. I notice that you have tried to get a policy based on Reaxys data in the aizynthfinder article, and I also plan to use Reaxys data to get a policy. How did you get the Reaxys data? Thank you.

**Comment by A-Thakkar** [comment]
Hi,

The Reaxys data was acquired under a licencing agreement with Elsevier. If you would like to use Reaxys data you will have to contact Elsevier and the Reaxys team directly to enquire and apply for a licence.

Unfortunately we are unable to help you in this process.

Amol

**Comment by queliyong** [comment]
> Hi,
> 
> The Reaxys data was acquired under a licencing agreement with Elsevier. If you would like to use Reaxys data you will have to contact Elsevier and the Reaxys team directly to enquire and apply for a licence.
> 
> Unfortunately we are unable to help you in this process.
> 
> Amol

Get it. Thank you for your advice.
