### ISSUE TITLE
ValueError: Atomic identity should not change in a reaction!

### ISSUE THREAD

**Issue by queliyong** [MolecularAI/aizynthfinder#33]
Hi, I retrained aizynthfinder based on the USPTO dataset, named '1976_Sep2016_USPTOgrants_smiles' and '2001_Sep2016_USPTOapplications_smiles'. After executing "preprocess_expansion" command (template_occurance: 5), I got about 60k unique templates. And then I carried out "aizynth_training config.yml expansion" command(using default training parameters). After 45 epochs, the model ended up with early stopping, and the tail epochs were as follows:

**epoch,accuracy,loss,top10_acc,top50_acc,top_k_categorical_accuracy,val_accuracy,val_loss,val_top10_acc,val_top50_acc,val_top_k_categorical_accuracy
41,0.37056171894073486,2.1262738704681396,0.9547296762466431,0.9979926347732544,0.8572583794593811,0.13169552385807037,3.383960247039795,0.8447669148445129,0.9704044461250305,0.6412613987922668
42,0.37039411067962646,2.1262192726135254,0.9547430276870728,0.9980724453926086,0.8570069670677185,0.13195891678333282,3.3870015144348145,0.8439049124717712,0.9697579145431519,0.6426501870155334
43,0.3698766529560089,2.1254725456237793,0.9548799991607666,0.9980325102806091,0.8570641875267029,0.1314081847667694,3.3882839679718018,0.8437373042106628,0.9703325629234314,0.6419557929039001
44,0.3700628876686096,2.1263396739959717,0.9547683000564575,0.998033881187439,0.8573368787765503,0.13179129362106323,3.3904759883880615,0.8440245985984802,0.9700692296028137,0.6423149704933167**

I doubt the model was not trained well since too low accuracy, but I could not find better training parameters.
The trained keras_model performs not bad for most target smiles in the tree search except for a few target smiles. In the GUI, a target smile got the following error:

_ValueError                                Traceback (most recent call last)
D:\software\anaconda\lib\site-packages\aizynthfinder\interfaces\aizynthapp.py in _tree_search(self)
    367     def _tree_search(self) -> None:
    368         with self._output["tree_search"]:
--> 369             self.finder.tree_search(show_progress=True)
    370             print("Tree search completed.")
    371 

D:\software\anaconda\lib\site-packages\aizynthfinder\aizynthfinder.py in tree_search(self, show_progress)
    197             leaf.expand()
    198             while not leaf.is_terminal():
--> 199                 child = leaf.promising_child()
    200                 if child:
    201                     child.expand()

D:\software\anaconda\lib\site-packages\aizynthfinder\mcts\node.py in promising_child(self)
    239         child = self._select_child(index)
    240         if not child and max(self._children_values) > 0:
--> 241             return self.promising_child()
    242 
    243         if not child:

D:\software\anaconda\lib\site-packages\aizynthfinder\mcts\node.py in promising_child(self)
    237         index = np.random.choice(indices)
    238 
--> 239         child = self._select_child(index)
    240         if not child and max(self._children_values) > 0:
    241             return self.promising_child()

D:\software\anaconda\lib\site-packages\aizynthfinder\mcts\node.py in _select_child(self, child_idx)
    372 
    373         reaction = self._children_actions[child_idx]
--> 374         if not reaction.reactants:
    375             reaction.apply()
    376 

D:\software\anaconda\lib\site-packages\aizynthfinder\chem.py in reactants(self)
    476         """
    477         if not self._reactants:
--> 478             self._reactants = self.apply()
    479         return self._reactants
    480 

D:\software\anaconda\lib\site-packages\aizynthfinder\chem.py in apply(self)
    487         :return: the products of the reaction
    488         """
--> 489         reaction = rdc.rdchiralReaction(self.smarts)
    490         rct = rdc.rdchiralReactants(self.mol.smiles)
    491         try:

D:\software\anaconda\lib\site-packages\rdchiral\initialization.py in __init__(self, reaction_smarts)
     42         if any(self.atoms_rt_map[i].GetAtomicNum() != self.atoms_pt_map[i].GetAtomicNum() \
     43                 for i in self.atoms_rt_map if i in self.atoms_pt_map):
---> 44             raise ValueError('Atomic identity should not change in a reaction!')
     45 
     46         # Call template_atom_could_have_been_tetra to pre-assign value to atom

ValueError: Atomic identity should not change in a reaction!_

Some target smiles showed the following RDKit ERROR when run search in the GUI:

**RDKit ERROR: 
RDKit ERROR: ****
RDKit ERROR: Pre-condition Violation
RDKit ERROR: attempt to add self-bond
RDKit ERROR: Violation occurred on line 300 in file D:\bld\rdkit_1591869558094\work\Code\GraphMol\RWMol.cpp
RDKit ERROR: Failed Expression: atomIdx1 != atomIdx2
RDKit ERROR: ****
RDKit ERROR: 
RDKit ERROR: [15:59:36] 
RDKit ERROR: 
RDKit ERROR: ****
RDKit ERROR: Pre-condition Violation
RDKit ERROR: attempt to add self-bond
RDKit ERROR: Violation occurred on line 300 in file D:\bld\rdkit_1591869558094\work\Code\GraphMol\RWMol.cpp
RDKit ERROR: Failed Expression: atomIdx1 != atomIdx2
RDKit ERROR: ****
RDKit ERROR: 
RDKit ERROR: [15:59:36] 
RDKit ERROR: 
RDKit ERROR: ****
RDKit ERROR: Pre-condition Violation
RDKit ERROR: attempt to add self-bond
RDKit ERROR: Violation occurred on line 300 in file D:\bld\rdkit_1591869558094\work\Code\GraphMol\RWMol.cpp
RDKit ERROR: Failed Expression: atomIdx1 != atomIdx2
RDKit ERROR: ****
RDKit ERROR:**

Any help would be appreciated!

**Comment by SGenheden** [comment]
Hello,
and thanks for your feedback.

I do not really understand why you are retraining the USPTO policy, as we have been publicly released such a policy.

You don't provide me with a lot of data to reproduce your errors. But to me it smells like you have some strange/funny/illegal SMARTS in your template library.

You can clearly see that the `ValueError` is raised when `aizynthfinder.chem.RetroReaction` is trying to initialize an RDChiral reaction from a SMARTS string. 

```
--> 489 reaction = rdc.rdchiralReaction(self.smarts)
---> 44 raise ValueError('Atomic identity should not change in a reaction!')
```

Therefore, one way for you to obtain some more information on what exact SMARTS it does not like, is to run a code that looks something like this:

```
import pandas as pd
from rdchiral import main as rdc
template_data = pd.read_hdf("path_to_unique_template_file.hdf5", "table")  # This file is the same as the second file you specify a policy in the config.yml
for smarts in template_data.retro_template.values:
    try:
        reaction = rdc.rdchiralReaction(smarts)
    except:
        print(f"Problem initializing {smarts}")
```

**Comment by queliyong** [comment]
> Hello,
> and thanks for your feedback.
> 
> I do not really understand why you are retraining the USPTO policy, as we have been publicly released such a policy.
> 
> You don't provide me with a lot of data to reproduce your errors. But to me it smells like you have some strange/funny/illegal SMARTS in your template library.
> 
> You can clearly see that the `ValueError` is raised when `aizynthfinder.chem.RetroReaction` is trying to initialize an RDChiral reaction from a SMARTS string.
> 
> ```
> --> 489 reaction = rdc.rdchiralReaction(self.smarts)
> ---> 44 raise ValueError('Atomic identity should not change in a reaction!')
> ```
> 
> Therefore, one way for you to obtain some more information on what exact SMARTS it does not like, is to run a code that looks something like this:
> 
> ```
> import pandas as pd
> from rdchiral import main as rdc
> template_data = pd.read_hdf("path_to_unique_template_file.hdf5", "table")  # This file is the same as the second file you specify a policy in the config.yml
> for smarts in template_data.retro_template.values:
>     try:
>         reaction = rdc.rdchiralReaction(smarts)
>     except:
>         print(f"Problem initializing {smarts}")
> ```

Hi,
Thank you for your advice. I would remove the problem template and retrain my policy. The main reason why I retrained USPTO data was I wanna trace the template_hash in the result of 'finder.routes.make_jsons()'  back to their PatentNumber, so as to make it clear that where the reactions of every route come from. My main confusion was that my trained policy ,based on 60k unique_templates, performed worse than the publicly policy in terms of most target smiles, which I'm sure based on just 40k unique_templates.  I finally used default training parameters, and I don't know how to further improve the training performance of my policy. Any advice would be appreciated.

**Comment by A-Thakkar** [comment]
Hi Queliyong,

Training performance generally tends to decrease at some point as you increase the template library size. You can refer to the following publication which highlights this issue and describes some of the studies we did when training the policies initially:

https://pubs.rsc.org/en/content/articlelanding/2019/sc/c9sc04944d#!divAbstract

To improve performance I recommend you shift to a multilabel approach with data augmentation which we have highlighted in the following manuscript:

https://iopscience.iop.org/article/10.1088/2632-2153/abcf90/meta

As to the original problem you faced with atom numbers, this is likely due to an invalid template. SMIRKS patterns should map atoms in the reactants to an atom in the product. For more information on the syntax i recommend the following resource:

https://www.daylight.com/dayhtml/doc/theory/theory.smirks.html

Regards,

Amol

**Comment by queliyong** [comment]
> Hi Queliyong,
> 
> Training performance generally tends to decrease at some point as you increase the template library size. You can refer to the following publication which highlights this issue and describes some of the studies we did when training the policies initially:
> 
> https://pubs.rsc.org/en/content/articlelanding/2019/sc/c9sc04944d#!divAbstract
> 
> To improve performance I recommend you shift to a multilabel approach with data augmentation which we have highlighted in the following manuscript:
> 
> https://iopscience.iop.org/article/10.1088/2632-2153/abcf90/meta
> 
> As to the original problem you faced with atom numbers, this is likely due to an invalid template. SMIRKS patterns should map atoms in the reactants to an atom in the product. For more information on the syntax i recommend the following resource:
> 
> https://www.daylight.com/dayhtml/doc/theory/theory.smirks.html
> 
> Regards,
> 
> Amol

Thank you very much. I'm following your advice.
