### ISSUE TITLE
AttributeError: 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by Zbless** [MolecularAI/aizynthfinder#36]
hi，
Sorry, there was an error in the problem submission on the last closed issue. So I reopened an issue. The problem was not described. When I execute the "app = aizynthapp (" / path / to / configFile. Yaml ")" statement, the following problems occur when loading the template. I tried to update the setuptools library, but I didn't solve the corresponding problem, so let's ask if there is any solution.

Loading expansion policy model from D:/py_project/AiZynthFinder/aizynthfinder/data/full_uspto_model.hdf5 to full_uspto
Loading templates from D:/py_project/AiZynthFinder/aizynthfinder/data/full_uspto_templates.hdf5 to full_uspto
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-4e52fb745a33> in <module>
      1 from aizynthfinder.interfaces import AiZynthApp
      2 configfile=r"D:\py_project\AiZynthFinder\aizynthfinder\config.yml"
----> 3 app = AiZynthApp(configfile)

D:\Program Files (x86)\Anaconda3\lib\site-packages\aizynthfinder\interfaces\aizynthapp.py in __init__(self, configfile, setup)
     56     def __init__(self, configfile: str, setup: bool = True) -> None:
     57         setup_logger(logging.INFO)
---> 58         self.finder = AiZynthFinder(configfile=configfile)
     59         self._input: StrDict = dict()
     60         self._output: StrDict = dict()

D:\Program Files (x86)\Anaconda3\lib\site-packages\aizynthfinder\aizynthfinder.py in __init__(self, configfile, configdict)
     46 
     47         if configfile:
---> 48             self.config = Configuration.from_file(configfile)
     49         elif configdict:
     50             self.config = Configuration.from_dict(configdict)

D:\Program Files (x86)\Anaconda3\lib\site-packages\aizynthfinder\context\config.py in from_file(cls, filename)
    110         with open(filename, "r") as fileobj:
    111             _config = yaml.load(fileobj.read(), Loader=yaml.SafeLoader)
--> 112         return Configuration.from_dict(_config)
    113 
    114     def update(self, **settings: Any) -> None:

D:\Program Files (x86)\Anaconda3\lib\site-packages\aizynthfinder\context\config.py in from_dict(cls, source)
     93             **source.get("filter", {}).get("files", {})
     94         )
---> 95         config_obj.stock.load_from_config(**source.get("stock", {}))
     96         config_obj.scorers.load_from_config(**source.get("scorer", {}))
     97 

D:\Program Files (x86)\Anaconda3\lib\site-packages\aizynthfinder\context\stock.py in load_from_config(self, **config)
    305             self.set_stop_criteria(config["stop_criteria"])
    306 
--> 307         for key, stockfile in config.get("files", {}).items():
    308             self.load(stockfile, key)
    309 

AttributeError: 'str' object has no attribute 'items'

**Comment by SGenheden** [comment]
Hello,

This looks like a problem with an incorrect config file.

As explained the in the documentation (https://molecularai.github.io/aizynthfinder/configuration.html), the format for the stock specification is

```
stock:
  files:
    zinc: zinc_stock.hdf5
```

that is the `files` key should point to a "dictionary" of key-value pairs.

The `AttributeError` you get is because `files` is followed by a string, not a dictionary. An example would be something like this:

```
stock:
  files: zinc_stock.hdf5 
```

Please make sure that your config file is in this format, and if the problem still happens, then please attach your config file to this ticket.

**Comment by Zbless** [comment]
oh,thank you. It is very useful to me.
