### ISSUE TITLE
Install instructions lead to installing old version

### ISSUE THREAD

**Issue by 5trigen** [MolecularAI/aizynthfinder#45]
Hey, this is just a minor heads up. I followed the install instructions in the README.md document under the "Troubleshooting" section, and the line:

python -m pip install https://github.com/MolecularAI/aizynthfinder/archive/v2.4.0.tar.gz

installs version 2.4.0. Once I found I had the old version I had no issues upgrading it, but I wanted to let you know about it because it is probably a very easy thing to fix and it might help out some people (like me) who simply copy and paste the install commands and don't read them thoroughly. Thank you in advance!

**Comment by SGenheden** [comment]
Hello and thank you very much.

Yes, it was an omission in the update procedure. It has now been corrected.
