### ISSUE TITLE
uspto_model.hdf5 is missing in the fileshare

### ISSUE THREAD

**Issue by jsooriya** [MolecularAI/aizynthfinder#48]
Could you pls share uspto_model.hdf5 in the fileshare.
Thanks in advance

**Comment by SGenheden** [comment]
Hello

I am not really sure what you want. In the README.md file of the repo, there are clear instructions under the heading `Usage` how to use the script `download_public_data` to obtain shared model files.

If anything is wrong with this script, please amend your issue.

**Comment by jsooriya** [comment]
Thank you very much for your Sincere response.
when i am running the script, I got following error. 
When I try to download directly from the url: "https://ndownloader.figshare.com/files/23086454"
I can download "full_uspto_03_05_19_rollout_policy.hdf5"
Am I missing something. 

Sorry for the inconvenience.
Regards
Sooriya.
----------------------------------------------------------------------------
(aizynth-env) administrator@BIO-LT-210:~/Downloads/aizynthfinder-3.0.0/Config$ download_public_data my_folder
uspto_model.hdf5:   0%|                                                                                                | 0.00/300M [00:00<?, ?B/s]Traceback (most recent call last):
  File "/home/administrator/miniconda3/envs/aizynth-env/bin/download_public_data", line 8, in <module>
    sys.exit(main())
  File "/home/administrator/miniconda3/envs/aizynth-env/lib/python3.8/site-packages/aizynthfinder/tools/download_public_data.py", line 70, in main
    _download_file(filespec["url"], os.path.join(path, filespec["filename"]))
  File "/home/administrator/miniconda3/envs/aizynth-env/lib/python3.8/site-packages/aizynthfinder/tools/download_public_data.py", line 51, in _download_file
    with open(filename, "wb") as fileobj:
FileNotFoundError: [Errno 2] No such file or directory: 'my_folder/uspto_model.hdf5'
uspto_model.hdf5:   0%|                                                                                                | 0.00/300M [00:00<?, ?B/s]
--------------------------------------------------------------------------------------------------------------------------------

**Comment by jsooriya** [comment]
Thank you. There is no problem, I made a mistake. 

I have found out the Error and resolved.
Its working fine.
Regards
Sooriya.
