### ISSUE TITLE
Incorparate AiZynthFinder in to own python script

### ISSUE THREAD

**Issue by pythonnewbie3** [MolecularAI/aizynthfinder#49]
Hello,
how can I incorperate AiZynthFinder into my own script. I have a program that predicts different molecular properties based on the SMILES and I also want suggest the user a synthesis route based on that.

**Comment by SGenheden** [comment]
Hello!

Perhaps this part of the documentation will be helpful to you: https://molecularai.github.io/aizynthfinder/python_interface.html

/ Sam

**Comment by pythonnewbie3** [comment]
Thank you this link seems really helpfull. Where can I find a working config.yml file. I guess it is the trained models?

**Comment by SGenheden** [comment]
The README on the landing page of the repo contains some useful information on how to obtain a working `config.yml` file and trained models + stock.

**Comment by pythonnewbie3** [comment]
Thank you. I'll check it out.
