### ISSUE TITLE
Error when applying retro_template to product

### ISSUE THREAD

**Issue by robertburbidgedata** [MolecularAI/aizynthfinder#5]
When running either aizynthcli or the GUI, I sometimes get the following error:

Traceback (most recent call last):
  File "xx/bin/aizynthcli", line 33, in <module>
    sys.exit(load_entry_point('aizynthfinder', 'console_scripts', 'aizynthcli')())
  File "xx/aizynthfinder/aizynthfinder/interfaces/aizynthcli.py", line 119, in main
    _process_multi_smiles(args.smiles, finder, args.output)
  File "xx/aizynthfinder/aizynthfinder/interfaces/aizynthcli.py", line 86, in _process_multi_smiles
    search_time = finder.tree_search()
  File "xx/aizynthfinder/aizynthfinder/aizynthfinder.py", line 176, in tree_search
    leaf = self.tree.select_leaf()
  File "xx/aizynthfinder/aizynthfinder/mcts/mcts.py", line 100, in select_leaf
    promising_child = current.promising_child()
  File "xx/aizynthfinder/aizynthfinder/mcts/node.py", line 232, in promising_child
    return self.promising_child()
  File "xx/aizynthfinder/aizynthfinder/mcts/node.py", line 230, in promising_child
    child = self._select_child(index)
  File "xx/aizynthfinder/aizynthfinder/mcts/node.py", line 311, in _select_child
    states = self._make_child_states(reaction)
  File "xx/aizynthfinder/aizynthfinder/mcts/node.py", line 287, in _make_child_states
    reactants_list = reaction.apply()
  File "xx/aizynthfinder/aizynthfinder/chem.py", line 279, in apply
    reactants = rdc.rdchiralRun(reaction, rct)
  File "xx/lib/python3.6/site-packages/rdchiral/main.py", line 242, in rdchiralRun
    merged_map_to_id[bj], b.GetBondType())
RuntimeError: Pre-condition Violation
        attempt to add self-bond
        Violation occurred on line 300 in file Code/GraphMol/RWMol.cpp
        Failed Expression: atomIdx1 != atomIdx2
        RDKIT: 2020.03.3
        BOOST: 1_67

For some reason I don't understand, RDChiral is failing when trying to apply the retro_template to the product. My workaround is to catch this in mcts/node.py:

    def _make_child_states(self, reaction):
        mols = [mol for mol in self.state.mols if mol is not reaction.mol]
        try:
            reactants_list = reaction.apply()
        except:
            reactants_list = None

I am training on Reaxys data and evaluating on the ChEMBL sample of 100 compounds. With this modification it solves 65 compounds.

**Comment by SGenheden** [comment]
Thanks for the feedback.
Could you try the new branch `bugfix-issue-5`? It is a variant on your solution.
If you use the `--log-to-file` switch to the `aizynthcli` tool it will print out the failed reaction to the debug log.
Do you mind sharing the failing template and product? If nothing else, I believe the developers of RDChiral would be interested if it is a truly a bug in their code.

**Comment by robertburbidgedata** [comment]
This is the last line of the log:

2020-09-08 11:52:42,685 - aizynthfinder - DEBUG - Reactants_list empty (), for mol O=C(ON1C(=O)CCC1=O)c1ccc2c(c1)OCO2 and transformation [C:4]-[O;H0;D2;+0:5]-[C;H0;D3;+0:1](=[O;D1;H0:2])-[c:3]>>Cl-[C;H0;D3;+0:1](=[O;D1;H0:2])-[c:3].[C:4]-[OH;D1;+0:5]

**Comment by SGenheden** [comment]
The SMARTS you quote above is invalid. You need to have brackets around the spec. for the first nitrogen. 

Otherwise, one get this exception:
`ValueError: ChemicalReactionParserException: Problems constructing reactant from SMARTS: [C:1]-N;H0;D3;+0:2-[O;H0;D2;+0:6]-[C:5]=[O;D1;H0:4]`

If I instead use "[C:1]-[N;H0;D3;+0:2]-[O;H0;D2;+0:6]-[C:5]=[O;D1;H0:4]>>[C:1]-[NH;D2;+0:2]-[C:3].[O;D1;H0:4]=[C:5]-[O;H0;D2;+0:6]-[O;H0;D2;+0:6]-[C:5]=[O;D1;H0:4]" I get the following exception
`KeyError: 3`

The exception is most likely due to the atom mapping. There is C3 to the right in the equation that is un-mapped, i.e. you are creating a carbon out of nothing. 

That is, I do not get the `RuntimeError` exception you reported at the top of this issue. This is the problem with using the bare `except`-clause that you introduced. You potentially hide a lot information.

**Comment by robertburbidgedata** [comment]
I take your point about my error handling.

I was printing reaction.smarts after reaction.apply() had thrown the error. If I print out the SMARTS beforehand, I get this:

[C:1]-[N;H0;D3;+0:2](-[C:3])-[O;H0;D2;+0:6]-[C:5]=[O;D1;H0:4]>>[C:1]-[NH;D2;+0:2]-[C:3].[O;D1;H0:4]=[C:5]-[O;H0;D2;+0:6]-[O;H0;D2;+0:6]-[C:5]=[O;D1;H0:4]

And in the logfile:

2020-09-08 13:43:12,290 - aizynthfinder - DEBUG - Runtime error in RDChiral with template [C:1]-[N;H0;D3;+0:2](-[C:3])-[O;H0;D2;+0:6]-[C:5]=[O;D1;H0:4]>>[C:1]-[NH;D2;+0:2]-[C:3].[O;D1;H0:4]=[C:5]-[O;H0;D2;+0:6]-[O;H0;D2;+0:6]-[C:5]=[O;D1;H0:4] on O=C(ON1C(=O)CCC1=O)c1ccc2c(c1)OCO2

My SMARTS templates were generated by RDChiral from SMILES reactions.

**Comment by robertburbidgedata** [comment]
I take your point about my error handling.

The above-quoted SMARTS was printed after reaction.apply() threw the error. If I print it out beforehand I get this:

[C:1]-[N;H0;D3;+0:2](-[C:3])-[O;H0;D2;+0:6]-[C:5]=[O;D1;H0:4]>>[C:1]-[NH;D2;+0:2]-[C:3].[O;D1;H0:4]=[C:5]-[O;H0;D2;+0:6]-[O;H0;D2;+0:6]-[C:5]=[O;D1;H0:4]

And in the logfile:

2020-09-08 13:43:12,290 - aizynthfinder - DEBUG - Runtime error in RDChiral with template [C:1]-[N;H0;D3;+0:2](-[C:3])-[O;H0;D2;+0:6]-[C:5]=[O;D1;H0:4]>>[C:1]-[NH;D2;+0:2]-[C:3].[O;D1;H0:4]=[C:5]-[O;H0;D2;+0:6]-[O;H0;D2;+0:6]-[C:5]=[O;D1;H0:4] on O=C(ON1C(=O)CCC1=O)c1ccc2c(c1)OCO2

The SMARTS were generated by RDChiral from SMILES reactions.

**Comment by robertburbidgedata** [comment]
I take your point about my error handling.

The SMARTS string is getting mangled when I paste it. It should be:

> [C:1]-[N;H0;D3;+0:2](-[C:3])-[O;H0;D2;+0:6]-[C:5]=[O;D1;H0:4]>>[C:1]-[NH;D2;+0:2]-[C:3].[O;D1;H0:4]=[C:5]-[O;H0;D2;+0:6]-[O;H0;D2;+0:6]-[C:5]=[O;D1;H0:4]

And in the logfile:

> 2020-09-08 13:43:12,290 - aizynthfinder - DEBUG - Runtime error in RDChiral with template [C:1]-[N;H0;D3;+0:2](-[C:3])-[O;H0;D2;+0:6]-[C:5]=[O;D1;H0:4]>>[C:1]-[NH;D2;+0:2]-[C:3].[O;D1;H0:4]=[C:5]-[O;H0;D2;+0:6]-[O;H0;D2;+0:6]-[C:5]=[O;D1;H0:4] on O=C(ON1C(=O)CCC1=O)c1ccc2c(c1)OCO2

The SMARTS were generated by RDChiral from SMILES reactions.

**Comment by robertburbidgedata** [comment]
I take your point about my error handling.

The SMARTS string is getting mangled when I paste it. It should be:

`[C:1]-[N;H0;D3;+0:2](-[C:3])-[O;H0;D2;+0:6]-[C:5]=[O;D1;H0:4]>>[C:1]-[NH;D2;+0:2]-[C:3].[O;D1;H0:4]=[C:5]-[O;H0;D2;+0:6]-[O;H0;D2;+0:6]-[C:5]=[O;D1;H0:4]
`

**Comment by SGenheden** [comment]
Thanks for fixing the formatting. 
This seems now like a pure RDChiral problem to me, the aizynthfinder tree search simply ignores the template gracefully, which I am satisfied with.
I think the SMARTS looks a little bit funny, but I'm no expert in cheminformatics.
Since you created the SMARTS with RDChiral, I suggest that you report the issue with the RDChiral repository.
