### ISSUE TITLE
how to set the atom occurrences limitations correctly 

### ISSUE THREAD

**Issue by queliyong** [MolecularAI/aizynthfinder#50]
Hi,
I wanna break down a target compound into very small molecules. So I limit the occurrence of atom "C" as 4. But there always seems to be a complex compound that can't be broken down further in the route, how can I do to figure it out?thanks.
![下载](https://user-images.githubusercontent.com/56716710/145151961-dd8ca213-68a7-4098-9690-46798863c4a5.png)

**Comment by SGenheden** [comment]
Hello,
The limit you are referring to is only used to modify the stop criteria of the search, not how intermediates are broken down. If a molecule cannot be broken down it is likely that a template is missing from the expansion policy, or that it has a very low probability. Looking at your target compound, I am not surprised that AiZynthFinder cannot properly break it down. This is a very unusual core, and aizynthfinder just goes into endless unproductive cycles of simple transformations like protection and deprotection. 
Have a look at the [Ringbreak](https://github.com/reymond-group/RingBreaker) project to see if this policy cannot break down your core.

**Comment by queliyong** [comment]
> Hello, The limit you are referring to is only used to modify the stop criteria of the search, not how intermediates are broken down. If a molecule cannot be broken down it is likely that a template is missing from the expansion policy, or that it has a very low probability. Looking at your target compound, I am not surprised that AiZynthFinder cannot properly break it down. This is a very unusual core, and aizynthfinder just goes into endless unproductive cycles of simple transformations like protection and deprotection. Have a look at the [Ringbreak](https://github.com/reymond-group/RingBreaker) project to see if this policy cannot break down your core.

Thanks for your helpful suggestion.
