### ISSUE TITLE
issue with importing from markupsafe

### ISSUE THREAD

**Issue by jtd1g16** [MolecularAI/aizynthfinder#57]
It appears that the new release of markupsafe breaks importing AiZynthFinder - link to the same issue in markupsafe: https://github.com/pallets/markupsafe/issues/284 

apparently v2.0.1 should work fine

edit: I tried swapping out the default installation of markupsafe with v2.0.1 and the aizynthfinder import works fine! :)

**Comment by SGenheden** [comment]
Thanks for notifying us about this.

The dependencies were updated in the latest patch release (v3.3.1), just released.
