### ISSUE TITLE
Pytables Dependency Issue on Windows 11

### ISSUE THREAD

**Issue by masyost** [MolecularAI/aizynthfinder#59]
Installing via env-users.yml on Windows 11 (21H2) (after modifying yml to point to code version 3.3.1 instead of 3.0.0), code throws an error within jupyter notebook related to a missing Pytables.

Using an identical installation process on macOS Monterey (12.3) does not exhibit this issue. Haven't tested Linux.

Installing pytables via conda resolves this issue:
`conda install -c conda-forge pytables`

Error copied from jupyter notebook:
[notebook_error.log](https://github.com/MolecularAI/aizynthfinder/files/8307703/notebook_error.log)

**Comment by SGenheden** [comment]
Thanks for the feedback.

I have added pytables to the yaml-files and fixed #58 as well. Apparently pip does not install the package well on Windows, so better to put the dependency in conda.

Could you be so kind and
1. Remove your conda environment
2. Try to reinstall it using `conda env create -f https://raw.githubusercontent.com/MolecularAI/aizynthfinder/yaml-updates/env-users.yml`

(It will use the yaml file in the development branch)

**Comment by SGenheden** [comment]
Thanks for trying out. I will merge the PR to master and close this and #58 as well
