### ISSUE TITLE
Simple Environment?

### ISSUE THREAD

**Issue by vthost** [MolecularAI/aizynthfinder#61]
Hi, Thank you so much for providing this tool (including all the documentation)!

Do you maybe have a minimal environment (e.g., w/o `pymongo`) which could work in most cases? I am trying to run a more  complex single-step model. When I first create the conda environment and include the packages I need in addition (e.g., `torchdrug`) everything installs, including the poetry steps afterwards. However, I do not manage to run my model in general in this environment and neither get it to run in aizynthfinder (resolving dependencies fails already, especially importing `torchdrug`), but get exceptions such as the below one. Now I think it would be worth to try with a minimal configuration. Or do you maybe have an idea which could be the critical packages? Thank you so much already!

```
libc++abi: terminating with uncaught exception of type std::length_error: vector
Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

**Comment by SGenheden** [comment]
Hello

Dependencies are always tricky, especially in Python. I don't have a minimal environment per se, but one could remove some that are not used by the core functionality like `pymongo` or `route-distances` and then you have to remove `import`-statements in the `aizynthfinder` package that are failing. 

A better solution would be to try to understand what dependencies of `aizynthfinder` and `torchdrug` interfere with one another. My guess it is either down to `pytorch` or `rdkit`, `pytorch` is a dependency of `route_distances` (which is a dependency of aizynthfinder) but the versions might not overlap. `rdkit` is installed by two different means with `aizynthfinder` and `torchdrug` which could cause some issues. 

I managed to create an environment in which `aizynthfinder` runs fine and in which I can do some simple `torchdrug` manipulations (I don't know what you are doing with `torchdrug`, so maybe this wouldn't work for you). I did:

```
conda create -n my-env python=3.8
conda activate my-env

# This command is taken from torchdrug Github page with the addition of poetry
conda install torchdrug poetry -c milagraph -c conda-forge -c pytorch -c pyg

cd REPO_FOLDER_AIZYNTHFINDER
rm poetry.lock
poetry install
```
