### ISSUE TITLE
pandas warning

### ISSUE THREAD

**Issue by drc007** [MolecularAI/aizynthfinder#63]
I suspect you know about this. I get a warning when using the cli

/Users/myname/miniconda3/envs/aizynth-env/lib/python3.8/site-packages/aizynthfinder/utils/files.py:48: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(new_data)

**Comment by SGenheden** [comment]
Thanks for the notification.

This will be updated in a future release. 

/ Sam

**Comment by SGenheden** [comment]
Fixed on master and will be included in release 3.4.0
