### ISSUE TITLE
Viewing Reaction Tree

### ISSUE THREAD

**Issue by cplateVT** [MolecularAI/aizynthfinder#67]
In the documentation under [Command Line Interface --> Analyzing Output], code is provided to generate images for reaction trees. Importing ReactionTree errors with the code written in the documentation:

>from aizynthfinder.analysis import ReactionTree

I think this was a typo and should say: 

>from aizynthfinder.reactiontree import ReactionTree

Replacing this line I was able to successfully generate reaction pathway images. Very useful software though! Thanks!

**Comment by SGenheden** [comment]
Thanks for pointing this out. 
You are absolutely correct, this was missed in a re-factoring drive.

**Comment by SGenheden** [comment]
Fixed on master and will be included in release 3.4.0
