### ISSUE TITLE
Scanner Error

### ISSUE THREAD

**Issue by Paulina-GM** [MolecularAI/aizynthfinder#68]
Hello,

I'm trying to use the Aizynthapp on the jupyter notebooks, using the documents provided in figshare. When I run the first cell I get the following error message: 

ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "<unicode string>", line 5, column 7:
          	full_uspto_03_05_19_unique_temp ...

I'm running this in a Linux cluster using python 3.8. If that's of any help.

Thanks in advance for your help.

**Comment by Paulina-GM** [comment]
Hi again,

Just a follow up. I was able to solve that issue by removing the tabs in the config file. but now I get the following error:

endosome/work/radiology/s187304/aizynth/aizynthfinder/aizynthfinder/context/policy/policies.py in load_from_config(self, **config)
    109         files_spec = config.get("files", config.get("template-based", {}))
    110         for key, policy_spec in files_spec.items():
--> 111             modelfile, templatefile = policy_spec
    112             strategy = TemplateBasedExpansionStrategy(
    113                 key, self._config, source=modelfile, templatefile=templatefile

ValueError: too many values to unpack (expected 2)

Thanks again in advance for your help.

**Comment by SGenheden** [comment]
Hello
Could you paste your config-file here? I don't understand how the tabs entered into your file, but the latest exceptions comes from a mal-formated config file. You should specify a policy using something like this
```
policy:
  files:
    my_policy:
      - path_to_model_file
      - path_to_template_file
```

**Comment by Paulina-GM** [comment]
Samuel,

Sorry I just realized I have some mistakes in the paths location,

I’m using as well the simplified version of the config file:

policy:
   files:
     my_policy:
       - full_uspto_03_05_19_rollout_policy.hdf5
       - full_uspto_03_05_19_unique_templates.hdf5
stock:
   files:
     zinc: zinc_stock.hdf5

And now my error is different:

OSError: No file or directory found at full_uspto_03_05_19_rollout_policy.hdf5

I do have the file in the aizynth forlder but I’ll see if there’s something else missing

Sorry for the basic questions. I’m just a chemist wanting to use machine learning but my experience is not that much.

Thanks in advance for your help

**Comment by Paulina-GM** [comment]
Samuel,

Sorry for the email bombing.

The program is working now!

Thank you very much eitherway.

Have a nice rest of the evening!

Paulina

**Comment by SGenheden** [comment]
Glad you could sort it out. I will close this ticket now.
Do not hesitate to return with more questions, even if you think they are basic.
I am glad it found its way to a chemists, and appreciate that you and other chemists are no computer specialists.

**Comment by Paulina-GM** [comment]
Samuel,

Thank you for your prompt response.

This is the config file I’m currently using

properties:
  iteration_limit: 100
  return_first: false
  time_limit: 120
  C: 1.4
  cutoff_cumulative: 0.995
  cutoff_number: 50
  max_transforms: 6
policy:
  files:
    my_policy:
      -/path/to/keras/model/weights.hdf5
      -/path/to/hdf5/templates.hdf5
filter:
  files:
    my_policy: /path/to/keras/model/weights.hdf5
  reactants_count:
    filter_tag:
stock:
  files:
    stock1: /path/to/stock1.hdf5
    stock2: /path/to/stock1.hdf5

**Comment by aa0929** [comment]
#I was very excited to try it and the previous error is gone, but a new one appeared
<img width="433" alt="image" src="https://github.com/MolecularAI/aizynthfinder/assets/45788520/3990d29b-ad93-4fc0-8795-25b82b099764">
<img width="898" alt="image" src="https://github.com/MolecularAI/aizynthfinder/assets/45788520/d3748a22-932b-4da7-991e-83687a3917f9">
<img width="890" alt="image" src="https://github.com/MolecularAI/aizynthfinder/assets/45788520/dd6d33d4-5849-4893-a84c-d29703a119db">
<img width="917" alt="image" src="https://github.com/MolecularAI/aizynthfinder/assets/45788520/c9ce87fa-00ae-487d-9253-a8ef05013fd6">
