### ISSUE TITLE
Suggestion for preprocess_rollout

### ISSUE THREAD

**Issue by robertburbidgedata** [MolecularAI/aizynthfinder#7]
I have a raw template library with ~15M rows. preprocess_rollout runs for ~1 day then fails in smiles_to_fingerprint. All my SMILES are valid, but a few cannot be sanitized. I could write a separate filter to prep the data, but I prefer to incorporate this into aizynthfinder in case I forget and lose another day:

aizynthfinder/training/utils.py:

```
14c14
< from aizynthfinder.chem import Molecule
---
> from aizynthfinder.chem import Molecule, MoleculeException
141a142,159
>
>
> def is_sanitizable(args):
>     """
>     Check whether a SMILES is sanitizable
>
>     :param args: the SMILES in the first element
>     :type args: tuple
>     :return: whether the SMILES is sanitizable
>     :rtype: bool
>     """
>     smiles = args[0]
>     try:
>         Molecule(smiles=smiles, sanitize=True)
>     except MoleculeException:
>         return False
>     else:
>         return True
```

aizynthfinder/training/preprocess_rollout.py:
```
--- 14,16 ----
      smiles_to_fingerprint,
+     is_sanitizable
  )
```
```
29a31,36
>
>     # remove rows with unsanitizable product SMILES
>     products = full_data["products"].to_numpy()
>     idx = np.apply_along_axis(is_sanitizable, 0, [products])
>     full_data = full_data[idx]
>
```

**Comment by SGenheden** [comment]
Thanks for the feedback.
I can consider include this is the package, however I would appreciate if you could prepare a PR.
In the PR, I also want include a setting in `default_training.yml` file called `remove_unsanitizable_products` that should be `False` by default. This flag should then be used to control if you remove the products or not. 
I would also like to have a unit test for this, but if you don't know how to write one - I can add one later.
