### ISSUE TITLE
Progress is displayed using multiple bars with one iteration

### ISSUE THREAD

**Issue by tagirshin** [MolecularAI/aizynthfinder#79]
Hello! So, I recently installed aizynthfinder and when I started `aizynthcli` with  standard parameters (except `time_limit` was equal to 600), it printed a lot of progress bars with only one iteration. I've tried with single and multiple processes. Here is an example of a log file:
![bug example](https://user-images.githubusercontent.com/17476642/183904697-5be40734-dbff-4334-add5-5c61e28edfed.png)
 
### Tool parameters:

- Version: 3.4.0
- Policy, reaction templates and stock are taken from [figshare](https://figshare.com/articles/dataset/AiZynthFinder_a_fast_robust_and_flexible_open-source_software_for_retrosynthetic_planning/12334577)
- Standard parameters, except `time_limit` equal to 600
- Command to start tool: `aizynthcli --config config.yml --smiles test.smi --nproc 20 --output new_test`

**Comment by SGenheden** [comment]
Thanks for reporting.
This issue appeared in a recent upgrade of tensorflow. I will push a fix to the master branch on Github today.
