### ISSUE TITLE
Problem with debugging simple linear policy network model

### ISSUE THREAD

**Issue by danisetiawan** [MolecularAI/aizynthfinder#81]
I tried to build a very simple policy network 'model' which contains only one reaction template, tried to run this using the target from the template and stock containing reactants from the template. This model is for testing purpose and thus are not trained. It gives probability of 1 for the single template use for the 'policy network'. However I got no routes solved, no MC tree generated and a very low state_score.  

There is no error message, which means the problem might not because of the model or the template. (I followed exactly the same protocol to process the template as I did with a different database, i.e. Pistachio, which works well)

Any idea of how to debug this?

**Comment by SGenheden** [comment]
This was interesting one. Interesting setup you have. 
Are you running this from the CLI or Jupyter?
I would suggest you start using the Python interface, if you are not already doing that: https://molecularai.github.io/aizynthfinder/python_interface.html
Then I would try the single-step retrosynthesis interface, `AiZynthExpander` and see if that produces the correct output. If that is the case, I might have other ideas how to debug this.

**Comment by SGenheden** [comment]
Closing this due inactivity
