### ISSUE TITLE
Hierarchy routes image not displaying

### ISSUE THREAD

**Issue by sitanshubhunia** [MolecularAI/aizynthfinder#85]
**Steps to Reproduce**
1.Environment
Windows11 
2. Open Command Prompt
conda activate aizynth-env
jupyter notebook

3. in Jupyter notebook cell write the below mentioned lines and hit enter 
from aizynthfinder.interfaces import AiZynthApp
app = AiZynthApp("E:\Data_AM\BAL\config.yml") 

4. In SMILES input, put 

[smiles.txt](https://github.com/MolecularAI/aizynthfinder/files/9618921/smiles.txt)

5. After that 
finder = app.finder
stats = finder.extract_statistics()

from aizynthfinder.interfaces.gui import ClusteringGui
ClusteringGui.from_app(app)

**Expected behavior**
 Hierarchy of the routes- image should display

_Note: What I am doing wrong._
**Actual behavior** 

![image](https://user-images.githubusercontent.com/840684/191567262-abe5327a-9093-4da2-9f7b-00842444a1e4.png)

**Comment by SGenheden** [comment]
Sorry for the late reply.
Try to use this code in the Notebook cell
```
%matplotlib inline
from aizynthfinder.interfaces.gui import ClusteringGui
ClusteringGui.from_app(app)
```

**Comment by sitanshubhunia** [comment]
@SGenheden Thanks. I am closing this.
