### ISSUE TITLE
Going over the max transforms limit 

### ISSUE THREAD

**Issue by tagirshin** [MolecularAI/aizynthfinder#89]
Hello! During analysis of tree search results I found out that if I use standard config without specifying max_transforms parameter, the tool can give me routes with 7 transformations instead of standard 6. Here is an example of a found pathway:
![route000](https://user-images.githubusercontent.com/17476642/195206552-84a2be8c-aca8-42c0-8d70-a45b54e124fe.png)

I tried to read the config file and on this side everything is fine:
<img width="637" alt="screenshot" src="https://user-images.githubusercontent.com/17476642/195207000-29e131b8-37ab-4356-86a9-7d3da994ffd8.png">

After I tried to browse through the code, but didn't catch the problem right away. I use the last version of aizynthfinder, taken from github. 

Also, regarding this issue, I don't understand how max_transforms and number_of_steps are related. From the docs I've got, that max_transforms is the max depth of the MCTS tree, but why then number_of_steps is needed?

**Comment by SGenheden** [comment]
I believe this is an old bug that has to do with the incorrect comparison operator being used. In some places in the code it should be "<" but it is "<=" that is implemented. We might update this, but in principle it doesn't affect the algorithm. One just has to reimagine what "max_transforms" is.

What is the "number_of_steps" you are referring to?

**Comment by tagirshin** [comment]
For example, when I read hdf5 file with results and statistics of a tree search, I have these columns:

![Screenshot](https://user-images.githubusercontent.com/17476642/203346774-78a4fb88-73aa-4ed5-85cd-c2b590a8fb1a.png)

So here I don't understand why max_transforms and number_of_steps are different

**Comment by SGenheden** [comment]
`max_transforms` refers to the depth of the MCTS search tree, i.e. it is a function over all routes extracted.
`number_of_steps` refers to the depth of top-ranked route

I will create an issue to add proper documentation for the output dictionaries.

**Comment by SGenheden** [comment]
Fixed by #141
