### ISSUE TITLE
Issue with checking stock and cyclic condition

### ISSUE THREAD

**Issue by bkbonde** [MolecularAI/aizynthfinder#9]
hi there,
seems there is a minor bug in your backpropagate function 
it seems you dont track the visited nodes in the tree and I guess with cyclic graph output it does get trapped in repeating pattern.
I guess one option is to check for visited nodes and if visited then terminate the search.

**Comment by SGenheden** [comment]
@bkbonde - do you have any updates to this or should I close the issue?

**Comment by bkbonde** [comment]
Hi Sam, 
I could not seems to reproduce with your recent update. I guess issue is resolved with updates. Please close the issue.

**Comment by SGenheden** [comment]
Ok. Thanks for trying it out again. Let me know if you re-discover it!
